### ISSUE TITLE
*All the users*?

### ISSUE THREAD

**Issue by exikyut** [getmanfred/dev-story-scraper#30]
I noticed this on HN a little while ago, and immediately wondered how hard it would be to simply just grab *everyone's* developer story (it's always fun to be able to turn around and go "here y'go :D"). I can see a decent bit of work has gone into this, and it would be a small shame for only a few people to benefit from it.

Sadly given the timing it looks like it's a bit 11th-hour to try and do *everything*, but I wonder what's maybe still possible.

After doing some digging and initially getting discouraged by custom URLs, I realized that you can basically access every non-hidden developer story indexed by user ID, ie `/story/12345678`.

Furthermore, the StackExchange Network data dumps (https://archive.org/download/stackexchange) includes an active list of StackOverflow users! Yay!

So I went off, downloaded that, extracted the user ids out, and started working on a little parallel downloader to start vacuuming everything up.

After a few hitches this worked grea`429 Too Many Requests`

*...noooooo :(*

I find I'm consistently hitting 429 after only a minute or two making requests 400ms apart, which doesn't feel fast enough.

If someone has access to (or is motivated enough to go sign up for) one of those scraping/proxy services, ...well that's probably the only sure-fire, realistic solution that would nail this given that there are approximately **17,053,414** *potential* pages (a \*large\* majority will 404, but they still need to be requested, and get past the rate limiter) - and 9 days left to fetch everything in. If someone is crazy enough to think that's interesting that I *might* be able to follow along (and, possibly, even help download a few things), but I frankly don't have the disposable income to kick it off myself.

In any case, it's not much, but... here:

**[userids.txt.xz.zip](https://github.com/getmanfred/dev-story-scraper/files/8344682/userids.txt.xz.zip)** (5MB)

Now you can skip wading through 5GB of XML, at least :v. ¯\\\_(ツ)\_/¯

<sub>(GitHub insisted on ZIP, which is... not quite in the ballpark of compression of XZ)</sub>

Caveat emptor: I wouldn't be surprised if the people working on this project have already gone down this path and identified everything in this issue. Perhaps the individual-download approach is a compromise based on that realization.

**Comment by ydarias** [comment]
Hello @exikyut 

We discarded that option because of ethical and legal implications.

> "Under the GDPR, we cannot (and we shouldn't) scrap personal data without direct permission"

We decided to offer this tool to our customers so they can import their data into [Manfred](https://getmanfred.com) and we saw no reason to not offer the tool to everyone that wants to download their own data without hosting them at Manfred.

**Your research work is incredible and amazing**! We want to say **thank you**!
